blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability Report
    url: mailto:security@terragonlabs.com
    about: Please report security vulnerabilities privately via email
  - name: Questions & Discussions
    url: https://github.com/terragonlabs/agentic-redteam-radar/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://agentic-redteam.readthedocs.io
    about: Check our comprehensive documentation for guides and API reference