name: Feature Request
description: Suggest a new feature for Agentic RedTeam Radar
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! We appreciate your input in making Agentic RedTeam Radar better.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're experiencing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: How should this feature work? What would it look like?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: Describe any alternative approaches you've considered

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which category best describes this feature?
      options:
        - Attack Patterns
        - Security Scanning
        - Reporting & Visualization
        - CI/CD Integration
        - Agent Framework Support
        - Performance & Optimization
        - API & SDK
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my adoption
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case
      placeholder: How would you use this feature? What's your workflow?
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would make this feature complete?
      placeholder: |
        - [ ] Feature should do X
        - [ ] Feature should support Y
        - [ ] Feature should integrate with Z

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Interest
      options:
        - label: I would be willing to help implement this feature
        - label: I can provide testing/feedback during development
        - label: I can help with documentation

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues for similar requests
          required: true
        - label: I have provided a clear problem statement and solution
          required: true
        - label: This feature aligns with the project's security testing mission
          required: true